export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const FETCH_PRODUCTS = "FETCH_PRODUCTS"
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const FILTER_PRODUCT_BY_SIZE = "FILTER_PRODUCT_BY_SIZE"
export const SORT_PRODUCT_BY_PRICE = "SORT_PRODUCT_BY_PRICE"